name: Build and Publish Binary
on:
    push:
        tags-ignore:
            - v1.*
    release:
        types: [published, created]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    compile_macOS_release:
        name: upload standard binary of macOS x86
        runs-on: macos-12

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 5
            - name: Configure
              run: |
                  mkdir build && cd build

            - name: Compile solc
              run: |
                  cd build
                  cmake -DCMAKE_BUILD_TYPE=Release ..
                  make -j2

            - name: Store binary
              run: |
                  ./build/solc/solc --version
                  mkdir bin
                  mv build/solc/solc bin/solc-mac
                  cd bin
                  tar -cvzf solc-mac.tar.gz solc-mac

            - name: Compile GM solc
              run: |
                  cd build && rm -rf CMakeCache.txt
                  cmake -DBUILD_GM=ON ..
                  make -j2

            - name: Store GM binary
              run: |
                  ./build/solc/solc --version
                  mv build/solc/solc bin/solc-mac-gm
                  cd bin
                  tar -cvzf solc-mac-gm.tar.gz solc-mac-gm

            - name: Upload solc binaries to release
              uses: svenstaro/upload-release-action@v1-release
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: bin/solc-mac.tar.gz
                  asset_name: solc-mac-x86.tar.gz
                  tag: ${{ github.ref }}
                  overwrite: true

            - name: Upload GM solc binaries to release
              uses: svenstaro/upload-release-action@v1-release
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: bin/solc-mac-gm.tar.gz
                  asset_name: solc-mac-x86-gm.tar.gz
                  tag: ${{ github.ref }}
                  overwrite: true

    compile_macOS_arm_release:
        name: upload standard binary of macOS arm64
        runs-on: macos-12

        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 5
            -   name: Configure
                run: |
                    mkdir build && cd build

            -   name: Compile solc
                run: |
                    cd build
                    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_PROCESSOR=aarch64 ..
                    make -j2

            -   name: Store binary
                run: |
                    ./build/solc/solc --version
                    mkdir bin
                    mv build/solc/solc bin/solc-mac
                    cd bin
                    tar -cvzf solc-mac.tar.gz solc-mac

            -   name: Compile GM solc
                run: |
                    cd build
                    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_PROCESSOR=aarch64 -DBUILD_GM=ON ..
                    make -j2

            -   name: Store GM binary
                run: |
                    ./build/solc/solc --version
                    mv build/solc/solc bin/solc-mac-gm
                    cd bin
                    tar -cvzf solc-mac-gm.tar.gz solc-mac-gm

            -   name: Upload solc binaries to release
                uses: svenstaro/upload-release-action@v1-release
                with:
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
                    file: bin/solc-mac.tar.gz
                    asset_name: solc-mac-arrch64.tar.gz
                    tag: ${{ github.ref }}
                    overwrite: true

            -   name: Upload GM solc binaries to release
                uses: svenstaro/upload-release-action@v1-release
                with:
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
                    file: bin/solc-mac-gm.tar.gz
                    asset_name: solc-mac-arrch64-gm.tar.gz
                    tag: ${{ github.ref }}
                    overwrite: true

    compile_windows_release:
        name: upload standard binary of Windows
        runs-on: windows-2019
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 5

            -   name: Add msbuild to PATH
                uses: microsoft/setup-msbuild@v2

            -   name: Configure and Compile solc
                run: |
                    mkdir build
                    cd build
                    cmake -G "Visual Studio 16 2019" ..
                    cmake --build . --config Release

            -   name: Store binary
                run: |
                    build\solc\Release\solc.exe --version
                    mkdir bin
                    move build\solc\Release\solc.exe bin\
                    cd bin
                    7z a solc-win.zip solc.exe

            -   name: Compile GM solc
                run: |
                    cd build
                    cmake -G "Visual Studio 16 2019" -DBUILD_GM=ON ..
                    cmake --build . --config Release

            -   name: Store GM binary
                run: |
                    build\solc\Release\solc.exe --version
                    move build\solc\Release\solc.exe bin\solc-gm.exe
                    cd bin
                    7z a solc-win-gm.zip solc-gm.exe

            -   name: Upload solc binaries to release
                uses: svenstaro/upload-release-action@v1-release
                with:
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
                    file: bin/solc-win.zip
                    asset_name: solc-win.zip
                    tag: ${{ github.ref }}
                    overwrite: true

            -   name: Upload GM solc binaries to release
                uses: svenstaro/upload-release-action@v1-release
                with:
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
                    file: bin/solc-win-gm.zip
                    asset_name: solc-win-gm.zip
                    tag: ${{ github.ref }}


    compile_centos_release:
        name: upload standard binary of centos
        runs-on: ubuntu-20.04
        container:
            image: centos:7
        steps:
            - name: Install dependencies
              run: |
                  yum install -y cmake3 gcc-c++ gmp-devel jsoncpp-devel leveldb-devel libcurl-devel lz4-devel ncurses-devel openssl-devel python3 wget
                  yum install -y centos-release-scl
                  yum install -y devtoolset-9
                  scl enable devtoolset-9 bash

            - uses: actions/checkout@v3
              with:
                  fetch-depth: 5

            - name: Configure and Compile solc
              run: |
                  mkdir build
                  cd build
                  cmake3 -DCMAKE_BUILD_TYPE=Release -DUSE_Z3=OFF ..
                  make -j2

            - name: Store binary
              run: |
                  build/solc/solc --version
                  mkdir bin
                  cp build/solc/solc bin/
                  cd bin
                  zip solc-centos-arm64.zip solc

            - name: Compile GM solc
              run: |
                  cd build
                  cmake3 -DCMAKE_BUILD_TYPE=Release -DUSE_Z3=OFF -DBUILD_GM=ON ..
                  make -j10 install

            - name: Store GM binary
              run: |
                  build/solc/solc --version
                  cp build/solc/solc bin/solc-gm
                  cd bin
                  zip solc-centos-arm64-gm.zip solc-gm

            - name: Upload solc binaries to release
              uses: svenstaro/upload-release-action@v1-release
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: bin/solc-centos-arm64.zip
                  asset_name: solc-centos-arm64.zip
                  tag: ${{ github.ref }}
                  overwrite: true

            - name: Upload GM solc binaries to release
              uses: svenstaro/upload-release-action@v1-release
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: bin/solc-centos-arm64-gm.zip
                  asset_name: solc-centos-arm64-gm.zip
                  tag: ${{ github.ref }}
