name: Build and Publish Binary
on:
    push:
        tags-ignore:
            - v1.*
    release:
        types: [published, created]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    compile_macOS_release:
        name: upload standard binary of macOS x86
        runs-on: macos-12

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 5
            - name: Configure
              run: |
                  mkdir build && cd build

            - name: Compile solc
              run: |
                  cd build
                  cmake -DCMAKE_BUILD_TYPE=Release ..
                  make -j2

            - name: Store binary
              run: |
                  ./build/solc/solc --version
                  mkdir bin
                  mv build/solc/solc bin/solc-mac
                  cd bin
                  tar -cvzf solc-mac.tar.gz solc-mac

            - name: Compile GM solc
              run: |
                  cd build && rm -rf CMakeCache.txt
                  cmake -DBUILD_GM=ON ..
                  make -j2

            - name: Store GM binary
              run: |
                  ./build/solc/solc --version
                  mv build/solc/solc bin/solc-mac-gm
                  cd bin
                  tar -cvzf solc-mac-gm.tar.gz solc-mac-gm

            - name: Upload solc binaries to release
              uses: svenstaro/upload-release-action@v1-release
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: bin/solc-mac.tar.gz
                  asset_name: solc-mac-x86.tar.gz
                  tag: ${{ github.ref }}
                  overwrite: true

            - name: Upload GM solc binaries to release
              uses: svenstaro/upload-release-action@v1-release
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: bin/solc-mac-gm.tar.gz
                  asset_name: solc-mac-x86-gm.tar.gz
                  tag: ${{ github.ref }}
                  overwrite: true

    compile_macOS_arm_release:
        name: upload standard binary of macOS arm64
        runs-on: macos-12

        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 5
            -   name: Configure
                run: |
                    mkdir build && cd build

            -   name: Compile solc
                run: |
                    cd build
                    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_PROCESSOR=aarch64 ..
                    make -j2

            -   name: Store binary
                run: |
                    ./build/solc/solc --version
                    mkdir bin
                    mv build/solc/solc bin/solc-mac
                    cd bin
                    tar -cvzf solc-mac.tar.gz solc-mac

            -   name: Compile GM solc
                run: |
                    cd build
                    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_PROCESSOR=aarch64 -DBUILD_GM=ON ..
                    make -j2

            -   name: Store GM binary
                run: |
                    ./build/solc/solc --version
                    mv build/solc/solc bin/solc-mac-gm
                    cd bin
                    tar -cvzf solc-mac-gm.tar.gz solc-mac-gm

            -   name: Upload solc binaries to release
                uses: svenstaro/upload-release-action@v1-release
                with:
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
                    file: bin/solc-mac.tar.gz
                    asset_name: solc-mac-arrch64.tar.gz
                    tag: ${{ github.ref }}
                    overwrite: true

            -   name: Upload GM solc binaries to release
                uses: svenstaro/upload-release-action@v1-release
                with:
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
                    file: bin/solc-mac-gm.tar.gz
                    asset_name: solc-mac-arrch64-gm.tar.gz
                    tag: ${{ github.ref }}
                    overwrite: true

    compile_windows_release:
        name: upload standard binary of Windows
        runs-on: windows-2019
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 5

            -   name: Add msbuild to PATH
                uses: microsoft/setup-msbuild@v2


            -   name: Configure and Compile solc
                run: |
                    mkdir build
                    cd build
                    cmake -G "Visual Studio 16 2019" -DUSE_Z3=OFF ..
                    msbuild solidity.sln /p:Configuration=Release

            -   name: Store binary
                run: |
                    build\solc\Release\solc.exe --version
                    mkdir bin
                    move build\solc\Release\solc.exe bin\
                    cd bin
                    7z a solc-win.zip solc.exe

            -   name: Compile GM solc
                run: |
                    cd build
                    cmake -G "Visual Studio 16 2019" -DUSE_Z3=OFF -DBUILD_GM=ON ..
                    cmake --build . -j 10 --target install --config Release

            -   name: Store GM binary
                run: |
                    build\solc\Release\solc.exe --version
                    move build\solc\Release\solc.exe bin\solc-gm.exe
                    cd bin
                    7z a solc-win-gm.zip solc-gm.exe

            -   name: Upload solc binaries to release
                uses: svenstaro/upload-release-action@v1-release
                with:
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
                    file: bin/solc-win.zip
                    asset_name: solc-win.zip
                    tag: ${{ github.ref }}
                    overwrite: true

            -   name: Upload GM solc binaries to release
                uses: svenstaro/upload-release-action@v1-release
                with:
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
                    file: bin/solc-win-gm.zip
                    asset_name: solc-win-gm.zip
                    tag: ${{ github.ref }}


    compile_centos_release:
        name: upload standard binary of centos
        runs-on: ubuntu-20.04
        container: docker.io/centos:7

        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 5

            -   name: Setup cmake
                uses: jwlawson/actions-setup-cmake@v1.14
                with:
                    cmake-version: '3.15.2'

            -   name: Configure
                run: |
                    yum install -y epel-release centos-release-scl 
                    yum update -y
                    yum install -y devtoolset-9 git wget build-essential clang flex bison patch glibc-static glibc-devel libzstd-devel libmpc cpp llvm-toolset-7 rh-perl530-perl cmake3 zlib-devel ccache lcov python-devel python3-devel
                    

            -   name: Compile solc
                run: |
                    tree /__w
                    cd /__w/solidity/
                    git log
                    . /opt/rh/devtoolset-9/enable
                    mkdir build && cd build
                    cmake -DCMAKE_BUILD_TYPE=Release -DUSE_Z3=OFF ..
                    make -j2

            -   name: Store binary
                run: |
                    ./build/solc/solc --version
                    mkdir bin
                    mv build/solc/solc bin/

            -   name: Compile GM solc
                run: |
                    cd build
                    cmake -DBUILD_GM=ON -DUSE_Z3=OFF ..
                    make -j2

            -   name: Store GM binary
                run: |
                    ./build/solc/solc --version
                    mv build/solc/solc bin/solc-gm

            -   name: Upload solc binaries to release
                uses: svenstaro/upload-release-action@v1-release
                with:
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
                    file: bin/solc
                    asset_name: solc-linux-x86
                    tag: ${{ github.ref }}
                    overwrite: true

            -   name: Upload GM solc binaries to release
                uses: svenstaro/upload-release-action@v1-release
                with:
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
                    file: bin/solc-gm
                    asset_name: solc-linux-x86-gm
                    tag: ${{ github.ref }}
                    overwrite: true
